"""CRUD layer (database queries).

Re-exports commonly used functions for convenience.
"""

from .users import (
    add_admin_shop,
    add_user,
    delete_user,
    get_all_admins,
    get_all_positions,
    get_all_shops,
    get_all_workers,
    get_admin_shops,
    get_employees_by_shop,
    get_employees_with_reports,
    get_user,
    get_user_by_pk,
    update_user,
)
from .checklists import (
    add_question,
    create_checklist,
    delete_checklist,
    delete_question,
    get_checklist,
    get_checklists,
    get_checklists_for_user,
    get_checklists_today,
    get_question,
    get_questions,
    update_checklist,
    update_question,
)
from .reports import (
    create_report,
    finish_report_calculation,
    get_all_reports_data,
    get_monthly_stats_by_shop,
    get_report_details,
    get_reports_by_checklist_id,
    get_reports_by_user_tg_id,
    get_today_completed_checklist_ids,
    save_answer_with_points,
)
from .analytics import (
    get_admin_activity_stats,
    get_admin_checklists,
    get_admin_workers,
    get_all_admins_activity,
    get_all_checklists_stats,
    get_all_workers_activity,
    get_checklists_by_shop,
    get_checklists_shops,
    get_network_overview_stats,
    get_workers_by_shop,
    get_workers_shops,
)

__all__ = [
    # users
    "get_user",
    "get_user_by_pk",
    "add_user",
    "add_admin_shop",
    "update_user",
    "delete_user",
    "get_all_positions",
    "get_all_workers",
    "get_all_admins",
    "get_all_shops",
    "get_admin_shops",
    "get_employees_by_shop",
    "get_employees_with_reports",
    # checklists
    "create_checklist",
    "update_checklist",
    "delete_checklist",
    "get_checklist",
    "get_checklists_for_user",
    "get_checklists",
    "get_questions",
    "get_question",
    "add_question",
    "update_question",
    "delete_question",
    "get_checklists_today",
    # reports
    "create_report",
    "save_answer_with_points",
    "finish_report_calculation",
    "get_monthly_stats_by_shop",
    "get_all_reports_data",
    "get_today_completed_checklist_ids",
    "get_reports_by_checklist_id",
    "get_report_details",
    "get_employees_with_reports",
    "get_reports_by_user_tg_id",
    # analytics
    "get_admin_activity_stats",
    "get_all_admins_activity",
    "get_all_workers_activity",
    "get_all_checklists_stats",
    "get_network_overview_stats",
    "get_admin_checklists",
    "get_admin_workers",
    "get_checklists_shops",
    "get_checklists_by_shop",
    "get_workers_shops",
    "get_workers_by_shop",
]
